cluster.name: my-elasticsearch
node.name: node1
path.data: [/var/elastic/data]
path.logs: [/var/elastic/logs]
bootstrap.system_call_filter: false
bootstrap.memory_lock: false
network.host: 192.168.1.1
http.host: 192.168.1.1
transport.bind_host: 192.168.1.1
discovery.zen.ping.unicast.hosts: ["192.168.1.1:9300","192.168.1.2:9300","192.168.1.3:9300"]
discovery.zen.minimum_master_nodes: 2
cluster.initial_master_nodes: ["node1","node2","node3"]
node.master: true
node.data: true
http.cors.enabled : true
http.cors.allow-origin : "*"
http.max_initial_line_length: 12kb
http.cors.allow-credentials: true
http.cors.allow-headers: WWW-Authenticate,X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
